pipeline {
  agent any
  tools { maven 'Maven' }

  stages {
    stage('Build') {
      steps {
        dir('my-java-project') {
          sh 'mvn -q clean package'
        }
      }
    }

    stage('Test') {
      steps {
        dir('my-java-project') {
          sh 'mvn -q test'
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        dir('my-java-project') {
          withSonarQubeEnv('SonarQube') {
            sh 'mvn -q sonar:sonar -Dsonar.projectKey=my-java-project -Dsonar.host.url=http://sonar:9000'
          }
        }
      }
    }
  }
}
