pipeline {
  agent any
  tools { maven 'Maven' }

  stages {
    stage('Build & Test') {
      steps {
        dir('my-java-project') {
          // compile + tests + génère target/site/jacoco/jacoco.xml
          sh 'mvn -q clean verify'
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        dir('my-java-project') {
          withSonarQubeEnv('SonarQube') {
            sh '''
              mvn -q sonar:sonar \
                -Dsonar.projectKey=my-java-project \
                -Dsonar.host.url=http://sonar:9000 \
                -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            '''
          }
        }
      }
    }
  }
}
